  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
    - go: tip
    fast_finish: true

  install:
    - sudo apt-get update -qq
    - sudo apt-get install upx
    - go get github.com/atrox/homedir
    - go get github.com/manifoldco/promptui
    - go get github.com/sirupsen/logrus
    - go get github.com/godbus/dbus
    - go get github.com/jessedp/lastseen-go/version
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
    - go get gopkg.in/yaml.v1
    - go get gopkg.in/natefinch/lumberjack.v2

  script:
    - make all
    - make cover
    - make release

  after_success:
      - bash <(curl -s https://codecov.io/bash)

  deploy:
    provider: releases
    api_key:
      secure: "g7USjPc5LsR7eKPS8noK7wTVIwANN1vkeVQN7rTdoQsrJoCWS544Flm0iWkePmVsVgx45ei2nJvn+FvEeQ8j8Ro/tZzmRjdn+e84QEIcKkWh2cgRlNN2PTUD+0L4D1G476vkQ/c66+rtlaFvhkZud7FQufQUdsB5QnT2uZLkwO/g9bxHiHgyqTCo/+PsmFpDl47kD3dzYIXESfFNVtfEwEot6NmN+3fDLw5kKlzeVzgqPRQIAxof8OmjTeaRTv5aG36cWeVmN/+mZyUlkdt4cXziRDOYPi7KrEnL+BKEp/dx1G7P0pDwTo4o0f75bjfi/MGmQadnE9/TAVUud9XpBi9RgBiq0tk5sha0L8Ds4usWUnDjf1cVYxn9vLT1OIeLwPqS5YxlV+7ahQ2wTlUNew4FXL3/gtTO9WAP8Gy8KDzVy+LX1tGRkuGxjDZx7Diwts557cV3PlOajuhJDBDFE17gvpnrJ7KRQ2Dw8BKOpYqCK4V7WI56uNFPNylgXzH25LIGdMWFo4YZtQ/LhdjUZ7s4mPe8IvUCfgw9vy3FbhWK2osK21+7P+ZgmNITHlaEmiKsdct5txwOb53lx6o0AARtKH7mzPFkTdwlbu4qXBvd7STnNu4R6bLMG3lJWTE+22ZtAylHQKCC9Z4CnQLes2ITAHf7HnWgwC2LLwFYLSc="
    file:
      - cross/lastseen-go-linux-amd64
      - cross/lastseen-go-linux-amd64.md5
      - cross/lastseen-go-linux-arm64.sha256
      - cross/lastseen-go-linux-arm
      - cross/lastseen-go-linux-arm.md5
      - cross/lastseen-go-linux-arm.sha256
      - cross/lastseen-go-linux-386
      - cross/lastseen-go-linux-386.md5
      - cross/lastseen-go-linux-386.sha256
      - cross/lastseen-go-linux-arm64
      - cross/lastseen-go-linux-arm64.md5
      - cross/lastseen-go-linux-amd64.sha256
    skip_cleanup: true
    on:
      tags: true
